spring.application.name=parallelisme

# INFO : headers de benchmark (stratégie + durée)
# DEBUG : détail par tâche (numéro + nom du thread)
logging.level.com.example.parallelisme=INFO

# Pour voir les noms de threads Reactor
logging.level.reactor.core=WARN
